# Generated by Django 5.0.3 on 2024-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
