# Generated by Django 5.0.3 on 2024-05-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_doctor_gender_alter_doctor_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="code",
        ),
    ]
