# Generated by Django 5.0.3 on 2024-05-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_patient_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="experience_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="license_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="work_days",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
