# Generated by Django 5.0.3 on 2024-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_doctor_experience_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="national_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="national_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
