# Generated by Django 5.0.3 on 2024-05-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_doctor_marital_status_and_more"),
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="enddatetime",
        ),
        migrations.AlterField(
            model_name="visit",
            name="doctors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="visits", to="accounts.doctor"
            ),
        ),
    ]
