# Generated by Django 5.0.3 on 2024-05-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="datatime",
        ),
        migrations.AddField(
            model_name="visit",
            name="end_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="start_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("done", "Done"),
                    ("canceled", "Canceled"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
