# Generated by Django 5.0.3 on 2024-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="measurement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Measurement",
        ),
    ]
