# Generated by Django 5.0.3 on 2024-05-15 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0004_remove_attachment_is_deleted_remove_visit_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
